# Generated by Django 4.1 on 2022-08-10 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(choices=[('Django Developer', 'Django Developer'), ('Angular Developer', 'Angular Developer'), ('QA Developer', 'QA Developer')], default='CharField', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_interviewer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'userprofile_table',
            },
        ),
    ]
