# Generated by Django 4.1 on 2022-08-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewschedule', '0002_interviewtimeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewtimeslot',
            old_name='is_allowed',
            new_name='is_allocated',
        ),
    ]
