# Generated by Django 4.1 on 2022-08-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewschedule', '0003_rename_is_allowed_interviewtimeslot_is_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
