# Generated by Django 4.1 on 2022-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewschedule', '0005_userprofile_first_time_login_userprofile_if_logged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtimeslot',
            name='available_slots',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
