# Generated by Django 4.1 on 2022-08-11 12:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interviewschedule', '0006_interviewtimeslot_available_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('scheduled_slots', models.JSONField(blank=True, default=dict, null=True)),
                ('interview_id', models.CharField(blank=True, max_length=30, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviewschedule.userprofile')),
            ],
            options={
                'db_table': 'interviewschedule_table',
            },
        ),
    ]
