# Generated by Django 4.1 on 2022-08-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewschedule', '0007_interviewschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='interviewers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewers', to='interviewschedule.userprofile'),
        ),
    ]
